### ISSUE TITLE
Concatenation of Key file is not idempotent

### ISSUE THREAD

**Issue by HenryGP** [HenryGP/om_ansible#29]
Las steps from `/root/tasks/ssl-creation.yaml` generate a PEM file with the cert and private key at the bottom. Multiple executions of the provisioning script result in this file not being correctly built hence the task is not idempotent. 

Need to explore `lineinfile` options or potential replacements to ensure that this works fine regardless the times it is executed.

**Comment by emisca** [comment]
why we don't simply rebuild the pem file at every execution?

I'll give a look at the code to see if I can fix it.

**Comment by emisca** [comment]
the example here can be useful, we can check the validity of the pem file and concatenate it only if needed:
https://api.playbook.cloud/v1/modules/openssl_certificate.html

**Comment by emisca** [comment]
with a lot of fatigue since I wasn't aware on how to access lists on ansible properly I made some code to check the presence of the pem key file and check if they the cert and the private key matches:
```
---
- name: Checking if server pem file exists
  stat: 
    path: /root/files/ssl/{{ item }}_server.pem
  register: serverpemstat
  with_items:
    - omserver
    - n1
    - n2
    - bkp
    - kmip
- debug:
    msg: File exists {{ item.stat.path }}
    verbosity: 2
  with_items: "{{ serverpemstat.results }}"
  when: item.stat.exists == true

- name: Get information on existing server pem files keys
  openssl_privatekey_info:
    path: "{{ item.stat.path }}"
  register: keyresult
  with_items: "{{ serverpemstat.results }}"
  when: item.stat.exists == true

- debug:
    var: keyresult
    verbosity: 2

- name: Get information on existing server pem files certs
  openssl_certificate_info:
    path: "{{ item.stat.path }}"
  register: certresult
  with_items: "{{ serverpemstat.results }}"
  when: item.stat.exists == true

- debug:
    var: certresult
    verbosity: 2

- debug:
    msg: Debug cert = {{ certresult.results[item == item.item] }} and key = {{ keyresult.results[item == item.item] }}
    verbosity: 0
  with_items: "{{ serverpemstat.results }}"
  when: item.stat.exists == true

- assert:
    that:
      - certresult.results[item == item.item].public_key == keyresult.results[item == item.item].public_key
  with_items: "{{ serverpemstat.results }}"
  when: item.stat.exists == true
```

now the next steps is to generate new certs only if the cert doesn't exist or if the key doesn't match.

**Comment by emisca** [comment]
uhm, it looks like I'm over complicating things as the only step that is not idempotent is the pem file creation.. sounds like I have the code necessary... WIP!

**Comment by emisca** [comment]
@HenryGP check my patch and if you wish merge it.

Do you have any idea on why this condition for the assert is evaluated also when the "when" condition is not matched:
```
- assert:
     that:
       - servercertresult.results[item == item.item].public_key == serverkeyresult.results[item == item.item].public_key
   with_items: "{{ serverpemstat.results }}"
   when: item.stat.exists == true
```
