### ISSUE TITLE
No hostname resolution between created containers

### ISSUE THREAD

**Issue by karl-denby** [HenryGP/om_ansible#3]
When you deploy via docker-compose, the created hosts have no way to talk to each other via hostname, this causes deployment of Replica Sets/Sharded Clusters to fail.

**Comment by HenryGP** [comment]
I think it was just a silly thing. I was naming the services differently so apparently `docker-compose` uses the service name for name resolution and this wasn't matching the actual hostname of the container I was creating. Doing some tests in branch `name-resolution` and will confirm and merge to master once done :)

**Comment by HenryGP** [comment]
#4
