### ISSUE TITLE
OM version option

### ISSUE THREAD

**Issue by mbarciela** [HenryGP/om_ansible#68]
Add the option to get the OM download URL automatically (om_download_url) by pointing out just OM version to be installed.

**e.g.**
```
om_version: X.X.XX
```

- Ansible vars
- Ansible tasks

**Comment by emisca** [comment]
this can be really difficult to do as we don't have a way to retrieve the OM RPM package URL list from the mongodb website, neither we know in a reliable way all the list of URLs.

A cheap way to do this is to make something similar to the version manifest we have for MongoDB with Ops Manager URLs.

**Comment by Airgunster** [comment]
@emisca, 
> this can be really difficult to do as we don't have a way to retrieve the OM RPM package URL list from the mongodb website, neither we know in a reliable way all the list of URLs.
We can actually do that, https://s3.amazonaws.com/info-mongodb-com/com-download-center/ops_manager_4.2.13.json (replace 4.2.13 with whatever version you want), that JSON is used by the Download Center (so it's trusted). I'll have a look how we can implement this.
