### ISSUE TITLE
Shell size too small

### ISSUE THREAD

**Issue by HenryGP** [HenryGP/om_ansible#8]
Probably related to tty and pty in Docker.
When connecting to a container using `docker exec -ti <container_name> /bin/bash` the shell is too small hence full screen utilities like `less` don't work as expected as characters are scrambled.

**Comment by HenryGP** [comment]
The behaviour is the same as attaching through a serial port to a running server.
Found out that this issue is not observed when connecting to the container running the following command:
```
bash -c "clear && docker exec -ti <container_name> /bin/bash"
```

**Comment by emisca** [comment]
this is fixed with the current docker version.
